#!/usr/bin/python

from sys import *
import pygame
import pygame.time
from pygame.locals import *
from pygame.colordict import THECOLORS
from random import randint

from molybear.map import Map
from molybear.sprite import SpriteCache
from molybear.texture import *
from molybear.entity import *

def update_oxygen(player):
		if player.oxygen > 0:
			player.oxygen -= .5

		if player.oxygen == 0:
			player.alive = False

		if (player.alive):
			status = "Oxygen: %d%%" % player.oxygen
		else:
			status = "Dead bear is dead"
		return status
	
def main():
	pygame.init()
	
	game_map = Map("map.txt")

	font = pygame.font.SysFont("monospace", 36, True)
	sprites = SpriteCache()
	screen = pygame.display.set_mode((32 * game_map.x, (32 * game_map.y) + 50))
	sprites.add_sheet(texture_files[0], 8, 8, (0, 255, 255))
	sprites.add_sheet(texture_files[1], 8, 8, (0, 255, 255))
	game_map.load_sprites(sprites)
	bg = pygame.image.load("textures/bg.png").convert()
	clock = pygame.time.Clock()
	
	entities = []
	player = Entity(3, 3, game_map, "P", "p", sprites, True)
	entities.append(Entity(6, 6, game_map, "H", "S", sprites))
	entities.append(Entity(3, 12, game_map, "H", "S", sprites))
	entities.append(Entity(6, 15, game_map, "H", "S", sprites))

	fps_goal = 30
	while True:
		clock.tick(fps_goal)


		status = update_oxygen(player)
		
		for e in pygame.event.get():
			if e.type == KEYDOWN:
				if e.key == K_UP:
					player.move_up()
				elif e.key == K_DOWN:
					player.move_down()
				elif e.key == K_LEFT:
					player.move_left()
				elif e.key == K_RIGHT:
					player.move_right()
				elif e.key == K_q:
					exit()

		# Draw the background, then the black area for text
		screen.fill((0, 0, 0))
		screen.blit(bg, (0, 0))
		game_map.draw_map(screen)
		
		for entity in entities:
			entity.move_wait += 1
			if entity.move_wait >= fps_goal/2 and entity.alive:
				x = randint(0, 10)
				if x <= 2:
					entity.move_left()
				elif x > 2 and x <= 4:
					entity.move_right()
				elif x > 4 and x <= 6:
					entity.move_up()
				elif x > 6 and x <= 8:
					entity.move_down()
				entity.move_wait = 0

			screen.blit(entity.get_sprite(), (entity.x * 32, entity.y * 32), None, 0)
		screen.blit(player.get_sprite(), (player.x * 32, player.y * 32), None, 0)
	
		font_surface = font.render(status, False, THECOLORS['white'])
		screen.blit(font_surface, (10, 520))
		pygame.display.flip()

		if not player.alive:
			pygame.time.wait(1000)
			pygame.event.wait()
			exit()

if __name__ == '__main__': main()


