#!/usr/bin/python

from sys import *
import pygame
import pygame.time
from pygame.locals import *
from pygame.colordict import THECOLORS
from random import randint

from molybear.map import Map
from molybear.sprite import SpriteCache
from molybear.texture import *
from molybear.entity import *

"""
	def move(self, key):
		new_x, new_y = self.pos_x, self.pos_y
		if key == K_UP:
			new_y = self.pos_y - 1
		elif key == K_DOWN:
			new_y = self.pos_y + 1
		elif key == K_LEFT:
			new_x = self.pos_x - 1
		elif key == K_RIGHT:
			new_x = self.pos_x + 1

		if self.validate_move(new_x, new_y):
			self.pos_x, self.pos_y = new_x, new_y

"""
def main():
	pygame.init()
	Entities = []
	
	game_map = Map("map.txt")

	sprites = SpriteCache()
	
	screen = pygame.display.set_mode((32 * game_map.x, (32 * game_map.y) + 50))
	sprites.add_sheet(texture_files[0], 8, 8, (0, 255, 255))
	sprites.add_sheet(texture_files[1], 8, 8, (0, 255, 255))
	game_map.load_sprites(sprites)
	
	entities = []
	player = Entity(3, 3, game_map, "P", "P", sprites)
	entities.append(Entity(6, 6, game_map, "H", "S", sprites))
	entities.append(Entity(3, 12, game_map, "H", "S", sprites))

	clock = pygame.time.Clock()
	while True:
		clock.tick(30)
		for e in pygame.event.get():
			if e.type == KEYDOWN:
				if e.key == K_UP:
					player.move_up()
				elif e.key == K_DOWN:
					player.move_down()
				elif e.key == K_LEFT:
					player.move_left()
				elif e.key == K_RIGHT:
					player.move_right()
				elif e.key == K_q:
					exit()
		game_map.draw_map(screen)

		for entity in entities:
			if entity.alive:
				x = randint(0, 10)
				if x <= 2:
					entity.move_left()
				elif x > 2 and x <= 4:
					entity.move_right()
				elif x > 4 and x <= 6:
					entity.move_up()
				elif x > 6 and x <= 8:
					entity.move_down()

			screen.blit(entity.get_sprite(), (entity.x * 32, entity.y * 32), None, 0)
		screen.blit(player.get_sprite(), (player.x * 32, player.y * 32), None, 0)
		pygame.display.flip()

if __name__ == '__main__': main()


